### ISSUE TITLE
NuGetPackages_GetPackagesAsync assumes the last downloaded datetime is not null

### ISSUE THREAD

**Issue by kirk-quinbar** [lvermeulen/ProGet.Net#44]
In a lot of cases, the last downloaded datetime will be null in a proget feed (at least in our scenario). the datetime should be nullable for that field.

Flurl.Http.FlurlHttpException
  HResult=0x80131500
  Message=Request to http://someprogetapi.com/json/NuGetPackages_GetPackages?key=xxxxxxxxxxxxxx&Feed_Id=2&PackageIds_Psv=SomePackageId failed. Error converting value {null} to type 'System.DateTime'. Path '[1].LastDownloaded_Date', line 1, position 2574.
  Source=Flurl.Http
  StackTrace:
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\HttpResponseMessageExtensions.cs:line 36
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 529
   at ProGet.Net.ProGetClient.<ExecuteNativeApiMethodAsync>d__6`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 529
   at ProGet.Net.ProGetClient.<NuGetPackages_GetPackagesAsync>d__87.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 351
   at NugetApi.Program.<ProGetUnlistAsync>d__7.MoveNext() in C:\Projects\gitlab\NugetApi\NugetApi\Program.cs:line 48
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 113
   at NugetApi.Program.<>c.<<Main>b__5_0>d.MoveNext() in C:\Projects\gitlab\NugetApi\NugetApi\Program.cs:line 29
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 113
   at NugetApi.Program.Main(String[] args) in C:\Projects\gitlab\NugetApi\NugetApi\Program.cs:line 27

Inner Exception 1:
JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path '[1].LastDownloaded_Date', line 1, position 2574.

Inner Exception 2:
InvalidCastException: Null object cannot be converted to a value type.

**Comment by lvermeulen** [comment]
Gotcha, will try and push a fix tonight.

**Comment by lvermeulen** [comment]
Release [1.0.1](https://github.com/lvermeulen/ProGet.Net/releases/tag/1.0.1)
